# Generated by Django 2.0 on 2020-03-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infra',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=300)),
                ('cast', models.CharField(max_length=800)),
                ('description', models.TextField(max_length=5000)),
                ('release_date', models.DateField()),
                ('averageRating', models.FloatField()),
                ('electricity', models.FloatField()),
                ('railways', models.TextField(max_length=1000)),
                ('bridges', models.FloatField()),
                ('tunnels', models.FloatField()),
                ('water_supply',models.CharField(max_length=1)),
                ('sewers', models.FloatField()),
                ('telecommunication', models.TextField(max_length=5000)),
                ('market', models.FloatField()),
                ('transportation', models.TextField(max_length=5000)),
                ('distributors', models.TextField(max_length=5000)),
                ('suppliers', models.TextField(max_length=5000)),
                ('mining_area', models.FloatField()),
                ('forest_area', models.FloatField()),
                ('ready_to_use_land', models.FloatField()),
            ],
        ),
    ]
