# Generated by Django 2.0 on 2021-10-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200324_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infra',
            name='bridges',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='distributors',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='electricity',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='forest_area',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='market',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='mining_area',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='railways',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='ready_to_use_land',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='sewers',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='suppliers',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='telecommunication',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='tunnels',
        ),
        migrations.RemoveField(
            model_name='infra',
            name='water_supply',
        ),
    ]
